### ISSUE TITLE
No tags are created

### ISSUE THREAD

**Issue by lucc** [alx741/vinfo#1]
I am using the latest Vinfo from git with neovim on Arch linux. But when I want to display a info file (`:Vinfo whatever`)  the tags are not converted correctly:
- No link targets are created. 
- The next and previous links at the top of each chapter are not marked as links. 
- The tags file is empty.
  Does this also happen for anyone else?

**Comment by alx741** [comment]
Haven't used Vinfo myself for a while, and I notice the latest Archlinux Neovim update changed (and broke) some things on my setup. Will take a look on that, thanks!

**Comment by alx741** [comment]
Apparently something changed with the `helptags` function. The same error appears in **vim-devicons** [here](https://github.com/ryanoasis/vim-devicons/issues/162), and was fixed by [removing unicode characters](https://github.com/ryanoasis/vim-devicons/pull/163)

**Comment by ryanwells-rwc** [comment]
There are also no tags with Vim and GVim 8.0.987 on Arch Linux.
Perhaps this is unrelated, but I'm also getting E149: "Sorry, no help for Vinfo."

**Comment by alx741** [comment]
@ryanwells-rwc apparently a lot of braking changes were introduced in the latest commits, I just revert them and committed a bug fix for the tags generation. Please try it out and let me know how it went.

About the `E149` error, does it come up when you `:h vinfo` ? How are you installing it?

**Comment by ryanwells-rwc** [comment]
@alx741 Awesome! The tags are working now.
Yes the `E149` comes up when executing `:h vinfo`.  I've installed it via Pathogen.

**Comment by alx741** [comment]
@ryanwells-rwc weird, but it seems like a Pathogen issue. I *think* you have to run `:Helptags`, check out this question: https://stackoverflow.com/questions/6970334/vim-pathogen-not-loading-help-docs.

Seems this particular issue is now solved, so I'm closing it. If any other problem emerges either related to the tags or the help, please open a new issue.
